"""Hard-negative prose, not forms, chat, signatures or OCR noise."""
NEGATIVE = {
    "en": {
        "invoice": ("Invoice number {x} was recorded for the stock shipment.", "The warehouse ledger lists invoice {x} for the goods."),
        "order": ("Order code {x} was assigned to the batch.", "The stock batch is tracked under order {x}."),
        "sku": ("Product identifier {x} appears on the package.", "The catalogue entry uses SKU {x}."),
        "version": ("The software release is version {x}.", "The installed application was upgraded to {x}."),
        "price": ("The product costs {x}.", "The catalogue gives the unit price as {x}."),
        "dimensions": ("The crate measures {x}.", "The dimensions of the display panel are {x}."),
        "date": ("The archive creation date is {x}.", "The historical schedule was published on {x}."),
        "time": ("The archived timetable starts at {x}.", "The recorded opening date and time are {x}."),
        "brand": ("The catalogue features the brand {x}.", "The shop stocks products made under the brand {x}."),
        "organisation": ("The organisation {x} supplies the equipment.", "The tender was awarded to the company {x}."),
        "place": ("The public exhibition venue is at {x}.", "The general visitor guide locates the museum at {x}."),
        "room": ("Room number {x} appears on the public station plan.", "The terminal guide points to gate {x}."),
        "statistics": ("The oldest machine is aged {x}.", "The average age of the stored equipment is {x} years."),
        "quantity": ("The shipment contains {x} units.", "The platform has a capacity of {x} crates."),
    },
    "de": {
        "invoice": ("Die Rechnungsnummer {x} wurde für die Warenlieferung erfasst.", "Das Lagerbuch nennt die Rechnung {x} für die Waren."),
        "order": ("Der Auftragscode {x} wurde der Charge zugewiesen.", "Die Warencharge wird unter dem Auftrag {x} geführt."),
        "sku": ("Die Produktkennung {x} steht auf der Verpackung.", "Der Katalogeintrag verwendet die Artikelnummer {x}."),
        "version": ("Die Softwareausgabe hat die Version {x}.", "Die installierte Anwendung wurde auf {x} aktualisiert."),
        "price": ("Das Produkt kostet {x}.", "Der Katalog nennt als Stückpreis {x}."),
        "dimensions": ("Die Kiste misst {x}.", "Die Abmessungen der Anzeigetafel betragen {x}."),
        "date": ("Das Erstellungsdatum des Archivs ist {x}.", "Der historische Fahrplan wurde am {x} veröffentlicht."),
        "time": ("Der archivierte Fahrplan beginnt am {x}.", "Das erfasste Öffnungsdatum mit Uhrzeit lautet {x}."),
        "brand": ("Der Katalog zeigt die Marke {x}.", "Der Laden verkauft Produkte unter der Marke {x}."),
        "organisation": ("Die Organisation {x} liefert die Ausrüstung.", "Der Auftrag wurde dem Unternehmen {x} erteilt."),
        "place": ("Der öffentliche Ausstellungsort liegt in {x}.", "Der allgemeine Besucherführer verortet das Museum in {x}."),
        "room": ("Die Raumnummer {x} steht auf dem öffentlichen Bahnhofsplan.", "Der Terminalführer weist auf das Flugsteig-Tor {x} hin."),
        "statistics": ("Die älteste Maschine ist {x} Jahre alt.", "Das Durchschnittsalter der gelagerten Geräte beträgt {x} Jahre."),
        "quantity": ("Die Lieferung enthält {x} Stück.", "Der Bahnsteig hat eine Kapazität von {x} Kisten."),
    },
    "fr": {
        "invoice": ("Le numéro de facture {x} a été enregistré pour la livraison du stock.", "Le registre de l'entrepôt indique la facture {x} pour les marchandises."),
        "order": ("Le code de commande {x} a été attribué au lot.", "Le lot de marchandises est suivi sous la commande {x}."),
        "sku": ("L'identifiant de produit {x} figure sur l'emballage.", "L'entrée du catalogue utilise la référence produit {x}."),
        "version": ("La publication du logiciel porte la version {x}.", "L'application installée a été mise à jour vers {x}."),
        "price": ("Le produit coûte {x}.", "Le catalogue indique un prix unitaire de {x}."),
        "dimensions": ("La caisse mesure {x}.", "Les dimensions du panneau d'affichage sont {x}."),
        "date": ("La date de création de l'archive est {x}.", "L'ancien calendrier a été publié le {x}."),
        "time": ("L'horaire archivé commence le {x}.", "La date et l'heure d'ouverture enregistrées sont {x}."),
        "brand": ("Le catalogue présente la marque {x}.", "Le magasin vend des produits de la marque {x}."),
        "organisation": ("L'organisation {x} fournit l'équipement.", "Le marché a été attribué à l'entreprise {x}."),
        "place": ("Le lieu public d'exposition se trouve à {x}.", "Le guide général des visiteurs situe le musée à {x}."),
        "room": ("Le numéro de salle {x} figure sur le plan public de la gare.", "Le guide du terminal indique la porte {x}."),
        "statistics": ("La plus ancienne machine est âgée de {x} ans.", "L'âge moyen des équipements stockés est de {x} ans."),
        "quantity": ("La livraison contient {x} unités.", "Le quai peut accueillir {x} caisses."),
    },
    "it": {
        "invoice": ("Il numero di fattura {x} è stato registrato per la consegna delle scorte.", "Il registro del magazzino indica la fattura {x} per le merci."),
        "order": ("Il codice d'ordine {x} è stato assegnato al lotto.", "Il lotto di merci è seguito con l'ordine {x}."),
        "sku": ("L'identificativo del prodotto {x} appare sulla confezione.", "La voce del catalogo usa il codice articolo {x}."),
        "version": ("L'edizione del programma ha la versione {x}.", "L'applicazione installata è stata aggiornata a {x}."),
        "price": ("Il prodotto costa {x}.", "Il catalogo indica il prezzo unitario di {x}."),
        "dimensions": ("La cassa misura {x}.", "Le dimensioni del pannello espositivo sono {x}."),
        "date": ("La data di creazione dell'archivio è {x}.", "Il calendario storico è stato pubblicato il {x}."),
        "time": ("L'orario archiviato inizia il {x}.", "La data e l'ora di apertura registrate sono {x}."),
        "brand": ("Il catalogo presenta il marchio {x}.", "Il negozio vende prodotti con il marchio {x}."),
        "organisation": ("L'organizzazione {x} fornisce l'attrezzatura.", "La gara è stata assegnata all'azienda {x}."),
        "place": ("La sede pubblica dell'esposizione si trova in {x}.", "La guida generale dei visitatori colloca il museo in {x}."),
        "room": ("Il numero della sala {x} appare sulla pianta pubblica della stazione.", "La guida del terminal indica l'uscita {x}."),
        "statistics": ("La macchina più vecchia ha {x} anni.", "L'età media delle attrezzature conservate è di {x} anni."),
        "quantity": ("La spedizione contiene {x} unità.", "Il binario ha una capacità di {x} casse."),
    },
    "es": {
        "invoice": ("El número de factura {x} se registró para la entrega del almacén.", "El registro del almacén indica la factura {x} para las mercancías."),
        "order": ("El código de pedido {x} se asignó al lote.", "El lote de mercancías se sigue con el pedido {x}."),
        "sku": ("El identificador de producto {x} aparece en el paquete.", "La entrada del catálogo usa el código de artículo {x}."),
        "version": ("La edición del programa lleva la versión {x}.", "La aplicación instalada se actualizó a {x}."),
        "price": ("El producto cuesta {x}.", "El catálogo indica un precio unitario de {x}."),
        "dimensions": ("La caja mide {x}.", "Las dimensiones del panel de exposición son {x}."),
        "date": ("La fecha de creación del archivo es {x}.", "El calendario histórico se publicó el {x}."),
        "time": ("El horario archivado comienza el {x}.", "La fecha y hora de apertura registradas son {x}."),
        "brand": ("El catálogo presenta la marca {x}.", "La tienda vende productos con la marca {x}."),
        "organisation": ("La organización {x} suministra el equipo.", "El contrato se adjudicó a la empresa {x}."),
        "place": ("El lugar público de la exposición está en {x}.", "La guía general de visitantes sitúa el museo en {x}."),
        "room": ("El número de sala {x} figura en el plano público de la estación.", "La guía de la terminal señala la puerta {x}."),
        "statistics": ("La máquina más antigua tiene {x} años.", "La edad media del equipo almacenado es de {x} años."),
        "quantity": ("El envío contiene {x} unidades.", "El andén tiene una capacidad de {x} cajas."),
    },
}


TRANSPORT = {
    "en": {"gate": ("Gate number {x} is printed on the airport map.", "The airport diagram labels gate {x}."),
           "platform": ("Platform number {x} is printed on the station map.", "The railway diagram labels platform {x}.")},
    "de": {"gate": ("Die Tornummer {x} steht auf dem Flughafenplan.", "Das Flughafenschema bezeichnet das Tor {x}."),
           "platform": ("Die Bahnsteignummer {x} steht auf dem Bahnhofsplan.", "Das Bahnschema bezeichnet den Bahnsteig {x}.")},
    "fr": {"gate": ("Le numéro de porte {x} est imprimé sur le plan de l'aéroport.", "Le schéma de l'aéroport indique la porte {x}."),
           "platform": ("Le numéro de quai {x} est imprimé sur le plan de la gare.", "Le schéma ferroviaire indique le quai {x}.")},
    "it": {"gate": ("Il numero di uscita {x} è stampato sulla mappa dell'aeroporto.", "Lo schema dell'aeroporto indica l'uscita {x}."),
           "platform": ("Il numero del binario {x} è stampato sulla mappa della stazione.", "Lo schema ferroviario indica il binario {x}.")},
    "es": {"gate": ("El número de puerta {x} está impreso en el plano del aeropuerto.", "El esquema del aeropuerto indica la puerta {x}."),
           "platform": ("El número de andén {x} está impreso en el plano de la estación.", "El esquema ferroviario indica el andén {x}.")},
}
for _language, _templates in TRANSPORT.items():
    NEGATIVE[_language].update(_templates)


def negative_template(language, split, kind):
    return NEGATIVE[language][kind][0 if split == "train" else 1]
