"""Two training and two genuinely held-out dev constructions per label."""
POSITIVE = {
    "en": {
        "PERSONNAME": ("Dear {x}, your personal application has been received.", "The applicant is {x}.", "We welcome the new member, {x}, to the private review.", "The person signing this letter is {x}."),
        "ADDRESS": ("The applicant lives at {x}.", "Please send the person's letter to {x}.", "Their complete home delivery address is {x}.", "The member has moved to {x}."),
        "EMAIL": ("Her email address is {x}.", "The applicant can be contacted at {x}.", "Please email the customer at {x}.", "His private mailbox is {x}."),
        "USERNAME": ("Her username is {x}.", "The member uses the handle {x}.", "The applicant signs in as {x}.", "His personal profile is registered under {x}."),
        "TELEPHONENUM": ("His telephone number is {x}.", "Please call the applicant on {x}.", "The member's private phone is {x}.", "She can be reached by telephone at {x}."),
        "IBAN": ("Her personal IBAN is {x}.", "Use {x} for the applicant's bank transfer.", "The member's bank account has IBAN {x}.", "His private banking record contains {x}."),
        "ACCOUNTNUM": ("Her bank account number is {x}.", "The applicant's savings account is {x}.", "The member holds personal account {x}.", "His private account is numbered {x}."),
        "CREDITCARDNUMBER": ("Her credit card number is {x}.", "The applicant paid with personal card {x}.", "The member's payment card bears {x}.", "His private card is numbered {x}."),
        "PASSPORTNUM": ("Her passport number is {x}.", "The applicant holds passport {x}.", "The member's travel document is passport {x}.", "His personal passport is numbered {x}."),
        "IDCARDNUM": ("Her identity card number is {x}.", "The applicant presented ID card {x}.", "The member's identity document bears {x}.", "His personal identity card is numbered {x}."),
        "DRIVERLICENSENUM": ("Her driving licence number is {x}.", "The applicant holds driving licence {x}.", "The member's driver's licence bears {x}.", "His personal driving permit is numbered {x}."),
        "TAXNUM": ("Her tax identification number is {x}.", "The applicant's personal tax number is {x}.", "The member is registered for tax under {x}.", "His private tax identifier is {x}."),
        "SOCIALNUM": ("Her social security number is {x}.", "The applicant's social insurance number is {x}.", "The member's social security record bears {x}.", "His personal social insurance identifier is {x}."),
        "PERSONALREF": ("Her customer number is {x}.", "The applicant has patient reference {x}.", "The member's personal case number is {x}.", "His private membership reference is {x}."),
        "DATEOFBIRTH": ("Her birth date is {x}.", "The applicant was born on {x}.", "The member's birthday is recorded as {x}.", "His date of birth is confirmed as {x}."),
        "AGE": ("The applicant is aged {x}.", "She is {x} years old.", "The member has reached the age of {x}.", "His current age is {x}."),
    },
    "de": {
        "PERSONNAME": ("Sehr geehrte {x}, Ihr persönlicher Antrag ist eingegangen.", "Die antragstellende Person heißt {x}.", "Wir begrüßen das neue Mitglied {x} zur persönlichen Prüfung.", "Diese Erklärung wird von {x} unterzeichnet."),
        "ADDRESS": ("Die antragstellende Person wohnt in {x}.", "Bitte senden Sie den privaten Brief an {x}.", "Die vollständige Wohnanschrift des Mitglieds lautet {x}.", "Die Person ist nach {x} umgezogen."),
        "EMAIL": ("Ihre E-Mail-Adresse lautet {x}.", "Die antragstellende Person ist unter {x} erreichbar.", "Bitte schreiben Sie dem Kunden an {x}.", "Sein privates E-Mail-Postfach ist {x}."),
        "USERNAME": ("Ihr Benutzername lautet {x}.", "Das Mitglied verwendet den Nutzernamen {x}.", "Die Person meldet sich als {x} an.", "Sein persönliches Profil ist unter {x} registriert."),
        "TELEPHONENUM": ("Seine Telefonnummer lautet {x}.", "Bitte rufen Sie die Person unter {x} an.", "Das private Telefon des Mitglieds hat die Nummer {x}.", "Sie ist telefonisch unter {x} erreichbar."),
        "IBAN": ("Ihre persönliche IBAN lautet {x}.", "Für die Überweisung der Person verwenden Sie {x}.", "Das Bankkonto des Mitglieds hat die IBAN {x}.", "Seine privaten Bankunterlagen enthalten {x}."),
        "ACCOUNTNUM": ("Ihre Kontonummer lautet {x}.", "Das Sparkonto der Person hat die Nummer {x}.", "Das Mitglied führt das persönliche Konto {x}.", "Sein Privatkonto ist mit {x} nummeriert."),
        "CREDITCARDNUMBER": ("Ihre Kreditkartennummer lautet {x}.", "Die Person zahlte mit ihrer privaten Karte {x}.", "Die Zahlungskarte des Mitglieds trägt {x}.", "Seine private Kreditkarte hat die Nummer {x}."),
        "PASSPORTNUM": ("Ihre Reisepassnummer lautet {x}.", "Die Person besitzt den Reisepass {x}.", "Das Reisedokument des Mitglieds ist der Pass {x}.", "Sein persönlicher Reisepass trägt die Nummer {x}."),
        "IDCARDNUM": ("Ihre Personalausweisnummer lautet {x}.", "Die Person legte den Ausweis {x} vor.", "Das Identitätsdokument des Mitglieds trägt {x}.", "Sein persönlicher Ausweis hat die Nummer {x}."),
        "DRIVERLICENSENUM": ("Ihre Führerscheinnummer lautet {x}.", "Die Person besitzt den Führerschein {x}.", "Die Fahrerlaubnis des Mitglieds trägt {x}.", "Sein persönlicher Führerschein hat die Nummer {x}."),
        "TAXNUM": ("Ihre Steueridentifikationsnummer lautet {x}.", "Die persönliche Steuernummer der Person ist {x}.", "Das Mitglied ist steuerlich unter {x} registriert.", "Seine private Steuerkennung lautet {x}."),
        "SOCIALNUM": ("Ihre Sozialversicherungsnummer lautet {x}.", "Die Sozialnummer der Person ist {x}.", "Die Sozialversicherung des Mitglieds führt {x}.", "Seine persönliche Versicherungsnummer lautet {x}."),
        "PERSONALREF": ("Ihre Kundennummer lautet {x}.", "Die Person hat die Patientennummer {x}.", "Das persönliche Aktenzeichen des Mitglieds ist {x}.", "Seine private Mitgliedsnummer lautet {x}."),
        "DATEOFBIRTH": ("Ihr Geburtsdatum lautet {x}.", "Die Person wurde am {x} geboren.", "Der Geburtstag des Mitglieds ist mit {x} eingetragen.", "Sein Geburtsdatum wurde als {x} bestätigt."),
        "AGE": ("Die Person ist {x} Jahre alt.", "Ihr Alter beträgt {x} Jahre.", "Das Mitglied hat das Alter von {x} Jahren erreicht.", "Sein derzeitiges Alter beträgt {x} Jahre."),
    },
    "fr": {
        "PERSONNAME": ("Bonjour {x}, votre demande personnelle a été reçue.", "La personne qui demande l'inscription est {x}.", "Nous accueillons le nouveau membre {x} pour l'examen privé.", "La personne qui signe cette lettre est {x}."),
        "ADDRESS": ("La personne habite à {x}.", "Veuillez envoyer sa lettre personnelle à {x}.", "L'adresse complète du domicile du membre est {x}.", "Cette personne a déménagé à {x}."),
        "EMAIL": ("Son adresse électronique est {x}.", "La personne est joignable à {x}.", "Veuillez écrire au client à {x}.", "Sa boîte électronique privée est {x}."),
        "USERNAME": ("Son nom d'utilisateur est {x}.", "Le membre utilise le pseudonyme {x}.", "La personne se connecte sous {x}.", "Son profil personnel est enregistré sous {x}."),
        "TELEPHONENUM": ("Son numéro de téléphone est {x}.", "Veuillez appeler cette personne au {x}.", "Le téléphone privé du membre porte le numéro {x}.", "Elle est joignable par téléphone au {x}."),
        "IBAN": ("Son IBAN personnel est {x}.", "Utilisez {x} pour le virement personnel du demandeur.", "Le compte bancaire du membre a pour IBAN {x}.", "Son dossier bancaire privé contient {x}."),
        "ACCOUNTNUM": ("Son numéro de compte bancaire est {x}.", "Le compte d'épargne du demandeur est {x}.", "Le membre possède le compte personnel {x}.", "Son compte privé porte le numéro {x}."),
        "CREDITCARDNUMBER": ("Son numéro de carte bancaire est {x}.", "La personne a payé avec sa carte personnelle {x}.", "La carte de paiement du membre porte {x}.", "Sa carte privée a pour numéro {x}."),
        "PASSPORTNUM": ("Son numéro de passeport est {x}.", "La personne possède le passeport {x}.", "Le document de voyage du membre est le passeport {x}.", "Son passeport personnel porte le numéro {x}."),
        "IDCARDNUM": ("Son numéro de carte d'identité est {x}.", "La personne a présenté la carte d'identité {x}.", "Le document d'identité du membre porte {x}.", "Sa carte d'identité personnelle a pour numéro {x}."),
        "DRIVERLICENSENUM": ("Son numéro de permis de conduire est {x}.", "La personne possède le permis de conduire {x}.", "Le permis du membre porte {x}.", "Son permis de conduire personnel a pour numéro {x}."),
        "TAXNUM": ("Son numéro fiscal est {x}.", "Le numéro fiscal personnel du demandeur est {x}.", "Le membre est enregistré pour l'impôt sous {x}.", "Son identifiant fiscal privé est {x}."),
        "SOCIALNUM": ("Son numéro de sécurité sociale est {x}.", "Le numéro d'assurance sociale du demandeur est {x}.", "Le dossier social du membre porte {x}.", "Son identifiant personnel de sécurité sociale est {x}."),
        "PERSONALREF": ("Son numéro de client est {x}.", "La personne a la référence patient {x}.", "Le numéro du dossier personnel du membre est {x}.", "Sa référence privée d'adhésion est {x}."),
        "DATEOFBIRTH": ("Sa date de naissance est {x}.", "La personne est née le {x}.", "L'anniversaire du membre est enregistré au {x}.", "Sa naissance a été confirmée au {x}."),
        "AGE": ("La personne est âgée de {x} ans.", "Elle a {x} ans.", "Le membre a atteint l'âge de {x} ans.", "Son âge actuel est de {x} ans."),
    },
    "it": {
        "PERSONNAME": ("Gentile {x}, la sua domanda personale è stata ricevuta.", "La persona che presenta la domanda è {x}.", "Accogliamo il nuovo membro {x} per la verifica privata.", "La persona che firma questa lettera è {x}."),
        "ADDRESS": ("La persona abita in {x}.", "Inviare la sua lettera personale a {x}.", "L'indirizzo completo di casa del membro è {x}.", "Questa persona si è trasferita in {x}."),
        "EMAIL": ("Il suo indirizzo email è {x}.", "La persona può essere contattata a {x}.", "Scrivere al cliente all'indirizzo {x}.", "La sua casella email privata è {x}."),
        "USERNAME": ("Il suo nome utente è {x}.", "Il membro usa il soprannome {x}.", "La persona accede come {x}.", "Il suo profilo personale è registrato come {x}."),
        "TELEPHONENUM": ("Il suo numero di telefono è {x}.", "Chiamare questa persona al {x}.", "Il telefono privato del membro ha il numero {x}.", "È raggiungibile telefonicamente al {x}."),
        "IBAN": ("Il suo IBAN personale è {x}.", "Usare {x} per il bonifico personale del richiedente.", "Il conto bancario del membro ha IBAN {x}.", "I suoi documenti bancari privati riportano {x}."),
        "ACCOUNTNUM": ("Il suo numero di conto bancario è {x}.", "Il conto di risparmio del richiedente è {x}.", "Il membro possiede il conto personale {x}.", "Il suo conto privato ha il numero {x}."),
        "CREDITCARDNUMBER": ("Il suo numero di carta di credito è {x}.", "La persona ha pagato con la carta personale {x}.", "La carta di pagamento del membro riporta {x}.", "La sua carta privata ha il numero {x}."),
        "PASSPORTNUM": ("Il suo numero di passaporto è {x}.", "La persona possiede il passaporto {x}.", "Il documento di viaggio del membro è il passaporto {x}.", "Il suo passaporto personale ha il numero {x}."),
        "IDCARDNUM": ("Il suo numero di carta d'identità è {x}.", "La persona ha presentato la carta d'identità {x}.", "Il documento di identità del membro riporta {x}.", "La sua carta d'identità personale ha il numero {x}."),
        "DRIVERLICENSENUM": ("Il suo numero di patente è {x}.", "La persona possiede la patente {x}.", "La patente del membro riporta {x}.", "La sua patente personale ha il numero {x}."),
        "TAXNUM": ("Il suo codice fiscale è {x}.", "Il numero fiscale personale del richiedente è {x}.", "Il membro è registrato ai fini fiscali con {x}.", "Il suo identificativo fiscale privato è {x}."),
        "SOCIALNUM": ("Il suo numero di previdenza sociale è {x}.", "Il numero di assicurazione sociale del richiedente è {x}.", "La posizione previdenziale del membro riporta {x}.", "Il suo identificativo previdenziale personale è {x}."),
        "PERSONALREF": ("Il suo numero cliente è {x}.", "La persona ha il riferimento paziente {x}.", "Il numero della pratica personale del membro è {x}.", "Il suo riferimento privato di iscrizione è {x}."),
        "DATEOFBIRTH": ("La sua data di nascita è {x}.", "La persona è nata il {x}.", "Il compleanno del membro è registrato al {x}.", "La sua nascita è stata confermata al {x}."),
        "AGE": ("La persona ha {x} anni.", "La sua età è di {x} anni.", "Il membro ha raggiunto l'età di {x} anni.", "La sua età attuale è {x} anni."),
    },
    "es": {
        "PERSONNAME": ("Estimado {x}, hemos recibido su solicitud personal.", "La persona que presenta la solicitud es {x}.", "Recibimos al nuevo miembro {x} para la revisión privada.", "La persona que firma esta carta es {x}."),
        "ADDRESS": ("La persona vive en {x}.", "Envíe su carta personal a {x}.", "La dirección completa del domicilio del miembro es {x}.", "Esta persona se ha mudado a {x}."),
        "EMAIL": ("Su dirección de correo es {x}.", "Se puede contactar con la persona en {x}.", "Escriba al cliente a {x}.", "Su buzón de correo privado es {x}."),
        "USERNAME": ("Su nombre de usuario es {x}.", "El miembro usa el alias {x}.", "La persona inicia sesión como {x}.", "Su perfil personal está registrado como {x}."),
        "TELEPHONENUM": ("Su número de teléfono es {x}.", "Llame a esta persona al {x}.", "El teléfono privado del miembro tiene el número {x}.", "Se la puede localizar por teléfono en {x}."),
        "IBAN": ("Su IBAN personal es {x}.", "Use {x} para la transferencia personal del solicitante.", "La cuenta bancaria del miembro tiene el IBAN {x}.", "Sus documentos bancarios privados contienen {x}."),
        "ACCOUNTNUM": ("Su número de cuenta bancaria es {x}.", "La cuenta de ahorro del solicitante es {x}.", "El miembro tiene la cuenta personal {x}.", "Su cuenta privada lleva el número {x}."),
        "CREDITCARDNUMBER": ("Su número de tarjeta de crédito es {x}.", "La persona pagó con su tarjeta personal {x}.", "La tarjeta de pago del miembro lleva {x}.", "Su tarjeta privada tiene el número {x}."),
        "PASSPORTNUM": ("Su número de pasaporte es {x}.", "La persona tiene el pasaporte {x}.", "El documento de viaje del miembro es el pasaporte {x}.", "Su pasaporte personal lleva el número {x}."),
        "IDCARDNUM": ("Su número de documento de identidad es {x}.", "La persona presentó la tarjeta de identidad {x}.", "El documento de identidad del miembro lleva {x}.", "Su tarjeta de identidad personal tiene el número {x}."),
        "DRIVERLICENSENUM": ("Su número de permiso de conducir es {x}.", "La persona tiene el permiso de conducir {x}.", "El permiso del miembro lleva {x}.", "Su permiso personal de conducir tiene el número {x}."),
        "TAXNUM": ("Su número de identificación fiscal es {x}.", "El número fiscal personal del solicitante es {x}.", "El miembro está registrado para impuestos con {x}.", "Su identificador fiscal privado es {x}."),
        "SOCIALNUM": ("Su número de seguridad social es {x}.", "El número de seguro social del solicitante es {x}.", "El expediente social del miembro lleva {x}.", "Su identificador personal de seguridad social es {x}."),
        "PERSONALREF": ("Su número de cliente es {x}.", "La persona tiene la referencia de paciente {x}.", "El número de expediente personal del miembro es {x}.", "Su referencia privada de afiliación es {x}."),
        "DATEOFBIRTH": ("Su fecha de nacimiento es {x}.", "La persona nació el {x}.", "El cumpleaños del miembro está registrado como {x}.", "Se ha confirmado que nació el {x}."),
        "AGE": ("La persona tiene {x} años.", "Su edad es de {x} años.", "El miembro ha alcanzado la edad de {x} años.", "Su edad actual es {x} años."),
    },
}


def positive_template(language, split, label, variant):
    offset = 0 if split == "train" else 2
    return POSITIVE[language][label][offset + variant]
