"""Fresh invented value pools and multilingual field-role vocabulary."""
NAMES = {
    "en": (("Evela", "Rovian", "Melora", "Tavien", "Sylena", "Orevyn"), ("Avriel", "Nevara")),
    "de": (("Alwina", "Rodelin", "Merlinde", "Tavolin", "Selwina", "Orenulf"), ("Arlinde", "Nevorin")),
    "fr": (("Éveline", "Rovien", "Mélorie", "Tavelle", "Sylène", "Orévane"), ("Avrielle", "Névane")),
    "it": (("Evelia", "Rovino", "Meloria", "Tavina", "Silenia", "Orevio"), ("Avriella", "Nevario")),
    "es": (("Evelia", "Rovián", "Meloria", "Taviela", "Silena", "Oreván"), ("Avriel", "Nevaira")),
}
SURNAMES = (("Veltrane", "Ordelune", "Cerovain", "Talveris", "Belorent", "Miravelle"),
            ("Azervelle", "Nocterain"))
STEMS = (("Elvaris", "Rovent", "Meluvar", "Taveril"), ("Arvess", "Nerovel", "Sylvarn", "Orvessa"))
CITIES = (("Elvorana", "Ravellune", "Melvessa", "Terenova"), ("Arvessia", "Nerovelis", "Sylvarnia", "Orvessara"))
CARDINALS = {
    "en": (("twenty-two", "twenty-six", "thirty-one", "thirty-five", "forty-two", "forty-six", "fifty-one", "fifty-five"), ("seventy-two", "seventy-six")),
    "de": (("zweiundzwanzig", "sechsundzwanzig", "einunddreißig", "fünfunddreißig", "zweiundvierzig", "sechsundvierzig", "einundfünfzig", "fünfundfünfzig"), ("zweiundsiebzig", "sechsundsiebzig")),
    "fr": (("vingt-deux", "vingt-six", "trente et un", "trente-cinq", "quarante-deux", "quarante-six", "cinquante et un", "cinquante-cinq"), ("soixante-douze", "soixante-seize")),
    "it": (("ventidue", "ventisei", "trentuno", "trentacinque", "quarantadue", "quarantasei", "cinquantuno", "cinquantacinque"), ("settantadue", "settantasei")),
    "es": (("veintidós", "veintiséis", "treinta y uno", "treinta y cinco", "cuarenta y dos", "cuarenta y seis", "cincuenta y uno", "cincuenta y cinco"), ("setenta y dos", "setenta y seis")),
}
NUMBERS = ((22, 26, 31, 35, 42, 46, 51, 55), (72, 76))
LOCALE = {
    "en": {"unit": "years", "particle": "de", "country": "United Kingdom", "dial": "44",
           "roads": ("Walk", "Crescent", "Terrace", "Grove"), "apartment": "suite", "care": "care of",
           "months": ("February", "May", "August", "November")},
    "de": {"unit": "Jahre", "particle": "von", "country": "Deutschland", "dial": "49",
           "roads": ("weg", "allee", "gasse", "ring"), "apartment": "Wohnung", "care": "bei",
           "months": ("Februar", "Mai", "August", "November")},
    "fr": {"unit": "ans", "particle": "de", "country": "France", "dial": "33",
           "roads": ("allée", "boulevard", "chemin", "impasse"), "apartment": "appartement", "care": "chez",
           "months": ("février", "mai", "août", "novembre")},
    "it": {"unit": "anni", "particle": "di", "country": "Italia", "dial": "39",
           "roads": ("viale", "vicolo", "corso", "piazza"), "apartment": "interno", "care": "presso",
           "months": ("febbraio", "maggio", "agosto", "novembre")},
    "es": {"unit": "años", "particle": "de", "country": "España", "dial": "34",
           "roads": ("paseo", "avenida", "camino", "plaza"), "apartment": "puerta", "care": "a cargo de",
           "months": ("febrero", "mayo", "agosto", "noviembre")},
}
# Four headers per field role, not imported stress-set strings.
ROLES = {
    "en": {"phone": ("Personal telephone", "Callback number", "Direct contact", "Recipient's phone"),
           "stock": ("Warehouse serial", "Catalogue revision", "Inventory item", "Product batch"),
           "qty": "Quantity", "price": "Unit cost", "contact": "Personal contact register",
           "objects": "Nonpersonal warehouse register", "note": "Route", "status": "Status"},
    "de": {"phone": ("Persönliche Telefonnummer", "Rückrufnummer", "Direkter Kontakt", "Telefon des Empfängers"),
           "stock": ("Lagerseriennummer", "Katalogrevision", "Inventarartikel", "Produktcharge"),
           "qty": "Menge", "price": "Stückpreis", "contact": "Persönliches Kontaktverzeichnis",
           "objects": "Sachliches Lagerverzeichnis", "note": "Route", "status": "Status"},
    "fr": {"phone": ("Téléphone personnel", "Numéro de rappel", "Contact direct", "Téléphone du destinataire"),
           "stock": ("Série du dépôt", "Révision du catalogue", "Article en stock", "Lot de produit"),
           "qty": "Quantité", "price": "Coût unitaire", "contact": "Registre des contacts personnels",
           "objects": "Registre du dépôt sans attribution personnelle", "note": "Circuit", "status": "État"},
    "it": {"phone": ("Telefono personale", "Numero per richiamare", "Contatto diretto", "Telefono del destinatario"),
           "stock": ("Serie di magazzino", "Revisione del catalogo", "Articolo in inventario", "Lotto del prodotto"),
           "qty": "Quantità", "price": "Costo unitario", "contact": "Registro dei contatti personali",
           "objects": "Registro di magazzino senza assegnazione personale", "note": "Percorso", "status": "Stato"},
    "es": {"phone": ("Teléfono personal", "Número de devolución de llamada", "Contacto directo", "Teléfono del destinatario"),
           "stock": ("Serie de almacén", "Revisión del catálogo", "Artículo de inventario", "Lote de producto"),
           "qty": "Cantidad", "price": "Coste unitario", "contact": "Registro de contactos personales",
           "objects": "Registro de almacén sin asignación personal", "note": "Ruta", "status": "Estado"},
}
FIELDS = {
    "en": {"birth": ("Date of birth", "Birth"), "calendar": ("Maintenance date", "Manufactured"),
           "private": "Recipient's home address", "specimen": "Exhibition specimen address",
           "personal": "Personal document wallet", "owner": "These documents belong to me",
           "operational": "Unassigned operational codebook", "phone_sample": "Nonpersonal serial sample",
           "documents": (("Driving permit identifier", "Permit"), ("Tax identification number", "Tax identifier"),
                         ("Membership reference", "Member number"), ("Social insurance identifier", "Social number")),
           "codes": ("Equipment operating permit", "Invoice batch identifier", "Assembly member count code", "Product compliance code")},
    "de": {"birth": ("Geburtsdatum", "Geburt"), "calendar": ("Wartungsdatum", "Herstellung"),
           "private": "Wohnanschrift des Empfängers", "specimen": "Ausstellungsadresse eines Musterobjekts",
           "personal": "Persönliche Dokumentenmappe", "owner": "Diese Dokumente gehören mir",
           "operational": "Nicht zugeordnetes Betriebscodebuch", "phone_sample": "Sachliches Serienmuster",
           "documents": (("Führerscheinkennung", "Fahrerlaubnis"), ("Steueridentifikationsnummer", "Steuerkennung"),
                         ("Mitgliedschaftsreferenz", "Mitgliedsnummer"), ("Sozialversicherungskennung", "Sozialnummer")),
           "codes": ("Betriebserlaubnis der Anlage", "Rechnungschargenkennung", "Bauteilzählcode", "Produktprüfcode")},
    "fr": {"birth": ("Date de naissance", "Naissance"), "calendar": ("Date de maintenance", "Fabrication"),
           "private": "Adresse du domicile du destinataire", "specimen": "Adresse du spécimen exposé",
           "personal": "Portefeuille de documents personnels", "owner": "Ces documents m'appartiennent",
           "operational": "Répertoire de codes opérationnels non attribués", "phone_sample": "Exemple de série non personnel",
           "documents": (("Identifiant du permis de conduire", "Permis"), ("Numéro d'identification fiscale", "Identifiant fiscal"),
                         ("Référence d'adhésion", "Numéro de membre"), ("Identifiant de sécurité sociale", "Numéro social")),
           "codes": ("Permis d'exploitation de machine", "Identifiant de lot de factures", "Code de quantité de composants", "Code de conformité du produit")},
    "it": {"birth": ("Data di nascita", "Nascita"), "calendar": ("Data di manutenzione", "Produzione"),
           "private": "Indirizzo di casa del destinatario", "specimen": "Indirizzo del campione esposto",
           "personal": "Portafoglio di documenti personali", "owner": "Questi documenti appartengono a me",
           "operational": "Repertorio di codici operativi non assegnati", "phone_sample": "Esempio di serie non personale",
           "documents": (("Identificativo della patente di guida", "Patente"), ("Numero di identificazione fiscale", "Codice fiscale"),
                         ("Riferimento di iscrizione", "Numero di socio"), ("Identificativo previdenziale", "Numero sociale")),
           "codes": ("Permesso operativo della macchina", "Identificativo del lotto di fatture", "Codice di quantità dei componenti", "Codice di conformità del prodotto")},
    "es": {"birth": ("Fecha de nacimiento", "Nacimiento"), "calendar": ("Fecha de mantenimiento", "Fabricación"),
           "private": "Dirección de casa del destinatario", "specimen": "Dirección del ejemplar expuesto",
           "personal": "Cartera de documentos personales", "owner": "Estos documentos me pertenecen",
           "operational": "Repertorio de códigos operativos sin asignar", "phone_sample": "Ejemplo de serie no personal",
           "documents": (("Identificador del permiso de conducir", "Permiso"), ("Número de identificación fiscal", "Identificador fiscal"),
                         ("Referencia de afiliación", "Número de socio"), ("Identificador de seguridad social", "Número social")),
           "codes": ("Permiso de funcionamiento del equipo", "Identificador del lote de facturas", "Código de cantidad de componentes", "Código de conformidad del producto")},
}
